### ISSUE TITLE
help paging with reactions bugged

### ISSUE THREAD

**Issue by cnschu** [Clemens-E/better-airhorn#430]
**as it is:**
1. $help
2. bot displays page 1 of help with <1 and >1
3. i click >1
4. help page 2 (music) is displayed with <1 and >2
5. to reach the next page i've to click >2 twice (1st to remove one reaction, then another time to reach the next page

**what it should be:**
1. $help
2. bot displays page 1 of help with <1 and >1
3. i click >1
4. help page 2 (music) is displayed with <1 and >2
5. bot removes my reaction, so that <1 and >1 is displayed
6. next or previous page can be reached by clicking just once

**Comment by Clemens-E** [comment]
Works fine for me, please make sure the bot has the "manage reactions" permissions.
If it still doesn't work let me know.

**Comment by cnschu** [comment]
For the first two pages it works fine, but not for the third (as described above).

You should perhaps include this permission into the bot config, so that it is given automatically with the invite 😄 

also i've not found such an permission, am i too blind?

**Comment by Clemens-E** [comment]
I can't reproduce this, only sometimes it takes 1-2 seconds, probably because discord is slow.

Either way I'm going away from that approach to have all commands in a single message, probably going to set up some kind of website. 

To be honest this version is rather dead, I'm not planning to make any large improvements to this code, because I'm planning to release the rewrite in 1-2 Weeks (I keep delaying it because of work and personal issues, but I have some weeks off over the holidays so)
If you want to make that version better and get some new features you can either join the [support server](https://github.com/Clemens-E/better-airhorn/blob/master/configs/config.ts#L37) or create issues to [this repo](https://github.com/better-airhorn/better-airhorn)

**Comment by cnschu** [comment]
why not use the project wiki site on github as help, and just post a link to the wiki?
No need for a separate page.

**Comment by Clemens-E** [comment]
Good idea, either GitHub wiki or wiki.js
